steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --dockerfile=bitnami/pgbouncer/1/debian-12/Dockerfile
    - --context=dir://${_SRC_DIRECTORY}/bitnami/pgbouncer/1/debian-12
    - --destination=gcr.io/$PROJECT_ID/${_REPO_NAME}/pgbouncer:$SHORT_SHA
    - --destination=gcr.io/$PROJECT_ID/${_REPO_NAME}/pgbouncer:latest
    - --cache=true
    - --cache-ttl=24h

images:
  - 'gcr.io/$PROJECT_ID/${_REPO_NAME}/pgbouncer'

substitutions:
  _BUILD_REGION: asia-southeast1
  _SRC_DIRECTORY: ./
  _REPO_NAME: bitnami-containers
