steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --dockerfile=bitnami/pgbouncer/1/debian-12/Dockerfile
    - --context=dir://${_SRC_DIRECTORY}/bitnami/pgbouncer/1/debian-12
    - --destination=gcr.io/$PROJECT_ID/${_REPO_NAME}/pgbouncer:$SHORT_SHA
    - --destination=gcr.io/$PROJECT_ID/${_REPO_NAME}/pgbouncer:latest
    - --cache=true
    - --cache-ttl=24h

- name: 'google/cloud-sdk:stable'
  script: |
    apt-get update && apt-get install -y git curl google-cloud-sdk-gke-gcloud-auth-plugin
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    gcloud source repos clone kube-manifest --project=itone-295207
    cd kube-manifest
    gcloud container clusters get-credentials itone-staging-cluster --zone asia-southeast1-a --project itone-295207 
    helm upgrade --dry-run pgbouncer-release \
     -f pgbouncer-conf/values.stage.yaml pgbouncer-conf/ \
     --set image.tag=$SHORT_SHA

substitutions:
  _BUILD_REGION: asia-southeast1
  _SRC_DIRECTORY: ./
  _REPO_NAME: bitnami-containers