apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: pgbouncer

build:
  artifacts:
    - image: pgbouncer
      context: bitnami/pgbouncer/1/debian-12
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: itone-295207
